Improve appbar and home view mobile view
clevaway/kemeet pull request #4
Opened 2021-11-05 20:40 UTC by jayeclark

Hello! I came across this issue and had some suggestions for improving the responsiveness of the app on mobile. The suggested changes in this pull request only affect the appnav component and the home view (there are still a few other components/views that need adjusting as well.)

Partially fixes #1 

**Regular layout**
<img width="760" alt="Screen Shot 2021-11-05 at 4 31 14 PM" src="https://user-images.githubusercontent.com/84106309/140574874-caa9dc86-e867-40d0-aad8-dabb4204fe03.png">

**Layout at 600px viewport width**
<img width="597" alt="Screen Shot 2021-11-05 at 4 31 31 PM" src="https://user-images.githubusercontent.com/84106309/140574890-cd9e3c53-e3c5-4fc2-bb00-224231bb1b75.png">

**Layout at 375 viewport width**
<img width="373" alt="Screen Shot 2021-11-05 at 4 31 51 PM" src="https://user-images.githubusercontent.com/84106309/140574913-acfc101b-e32f-443a-b933-855851ad0ef5.png">

2021-11-05 21:14 UTC, FotieMConstant requested changes
Hi @jayeclark thanks for this amazing PR, You have done some awesome work right there... I love the fact that you suggested a clean responsive design for the app. I also noticed you wrote raw CSS in the tailwind.css folder, could you please make a separate file for costume CSS as we only import the tailwind assets on here. Would love to keep some consistency along the way :)  Also, down along the line, we will be using more tailwind for the styling and very little costume CSS.

Please could you fix that so I can merge your changes?
Thanks for this amazing contribution.

Regards, Fotie.

2021-11-05 21:23 UTC, jayeclark commented
@FotieMConstant Yes, sure, makes sense. I'm signing off for the day right now but will work on it tomorrow. I most likely can accomplish similar changes without needing to create any new CSS classes.

2021-11-05 21:25 UTC, FotieMConstant commented
If we can do that with tailwind that would be awesome.

2021-11-05 23:18 UTC, jayeclark commented
@FotieMConstant Yes, now that I think about it the changes almost certainly should be possible using only tailwind, the disadvantages are 1) more extensive/verbose class lists and 2) the breakpoints might not be quite as ideal. But those are both acceptable trade-offs if you want to avoid creating custom classes.

2021-11-06 05:58 UTC, FotieMConstant commented
We certainly can't do everything with tailwind. What can't be done with tailwind would be wrapped in a costume class :)

2021-11-06 05:59 UTC, FotieMConstant commented
I'm having a day off today, hence I'll be focusing on building responsive for the meeting view.

2021-11-06 13:30 UTC, jayeclark commented
@FotieMConstant Redid the PR to achieve the responsive design using only Tailwind, no custom classes needed!

2021-11-06 15:15 UTC, FotieMConstant commented
@jayeclark you are amazing. Thanks a million for the contribution :)

2021-11-06 15:18 UTC, FotieMConstant approved these changes

2021-11-06 15:19 UTC, merged